config/routes.rb
Rails.application.routes.draw do
  resources :employee_roles
  
  resources :projects
  
  resources :blogs
  

  resources :employee_ratings


  root to: "projects#index"
  #devise_for :users
  devise_for :users, controllers: {registrations: 'users/registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  
  def initialize(employee_role)
    employee_role ||= Employee_Role.new
    if employee_role.manager?
      can :manage, :all
    elsif employee_role.devloper?
      can :read, Project
      can :create, Project
      can :update, Project
      can :destroy, Project do |project|
        project.try(:employee_role) == employee_role
    end    
    elsif employee_role.tester?
      can :read, Project
      can :update, Project do |project|
      project.try(:employee_role) == employee_role
    end
    elsif employee_role.lead?
      can :manage, :devloper
    end  

         
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/employee_rating.rb
class EmployeeRating < ApplicationRecord
end

app/models/employee_role.rb
class EmployeeRole < ApplicationRecord

end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user 
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable
         has_one :profile, dependent: :destroy
         accepts_nested_attributes_for :profile, allow_destroy: true
         
         has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    def index
        @blogs = Blog.all
        end
        def show
        @blog = Blog.find(params[:id])
        end
        def new
        @blog=Blog.new
        end
        def create
        @blog = Blog.new(blog_params)
        if @blog.save
        redirect_to blogs_path
        else
        render :new
        end
        end
        def edit
        @blog=Blog.find(params[:id])
        end
        def update
        @blog = Blog.find(params[:id])
        if @blog.update(blog_params)
        redirect_to blogs_path
        else
        render :edit
        end
        end
        def destroy
        @blog = Blog.find(params[:id])
        @blog.destroy
        redirect_to blogs_path
        end
        private
        def blog_params
        params.require(:blog).permit(:posts, :comments, :username)
        end
end

app/controllers/employee_ratings_controller.rb
class EmployeeRatingsController < ApplicationController
    def index
        @employee_ratings = EmployeeRating.all
        end
        def show
        @employee_rating = Employee_raiting.find(params[:id])
        end
        def new
        @employee_rating=EmployeeRating.new
        end
        def create
        @employee_rating = EmployeeRating.new(employee_rating_params)
        if @employee_rating.save
        redirect_to employee_ratings_path
        else
        render :new
        end
        end
        def edit
        @employee_rating=EmployeeRating.find(params[:id])
        end
        def update
        @employee_rating = EmployeeRating.find(params[:id])
        if @employee_rating.update(employee_params)
        redirect_to employee_ratings_path
        else
        render :edit
        end
        end
        def destroy
        @employee_rating = EmployeeRating.find(params[:id])
        @employee_rating.destroy
        redirect_to employee_ratings_path
        end
        private
        def employee_rating_params
        params.require(:employee_rating).permit(:username,:rating, :reporting_manager)
        end
end

app/controllers/employee_roles_controller.rb
class EmployeeRolesController < ApplicationController
  
  def index
      @employee_roles = EmployeeRole.all
      end
      def show
      @employee_role = EmployeeRole.find(params[:id])
      end
      def new
      @employee_role=EmployeeRole.new
      end
      def create
      @employee_role = EmployeeRole.new(employee_role_params)
      if @employee_role.save
      redirect_to employee_roles_path
      else
      render :new
      end
      end
      def edit
      @employee_role=EmployeeRole.find(params[:id])
      end
      def update
      @employee_role = EmployeeRole.find(params[:id])
      if @employee_role.update(employee_role_params)
      redirect_to employee_roles_path
      else
      render :edit
      end
      end
      def destroy
      @employee_role = EmployeeRole.find(params[:id])
      @employee_role.destroy
      redirect_to employee_roles_path
      end
      private
      def employee_role_params
        params.require(:employee_role).permit(:name, :role)
      end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def index
        @projects = Project.all
        end
        def show
        @project = Project.find(params[:id])
        end
        def new
        @project=Project.new
        end
        def create
        @project = Project.new(project_params)
        if @project.save
        redirect_to projects_path
        else
        render :new
        end
        end
        def edit
        @project=Project.find(params[:id])
        end
        def update
        @project = Project.find(params[:id])
        if @project.update(project_params)
        redirect_to projects_path
        else
        render :edit
        end
        end
        def destroy
        @project = Project.find(params[:id])
        @project.destroy
        redirect_to projects_path
        end
        private
        def project_params
        params.require(:project).permit(:name, :duration, :total_team)
        end
        end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    before_action :sign_up_params, only: [:create]
    before_action :account_update_params, only: [:update]
    def new
    puts "\n\n...Im in ur local...\n\n"
    build_resource({})
resource.build_profile
respond_with self.resource
end
def create
super
end
def update
super
end
private
def sign_up_params
devise_parameter_sanitizer.sanitize(:sign_up)
params.require(:user).permit(:email, :password, :password_confirmation,
profile_attributes: [:firstname, :lastname])
end
def account_update_params
params.require(:user).permit(:current_password, :email, :password,
:password_confirmation, profile_attributes: [ :firstname, :lastname
])
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/employee_ratings_helper.rb
module EmployeeRatingsHelper
end

app/helpers/employee_roles_helper.rb
module EmployeeRolesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/blogs/_form.html.erb
<%= form_for @blog do |f| %>
<br>
    <div>
    <%= f.label :posts %>
    <%= f.text_field :posts %>
    </div>
    <br>
    <div>
    <%= f.label :comments %>
    <%= f.text_field :comments %>
    </div>
    <br>
    <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
    </div>
    <br>
    <div>
    <%= f.submit %>
    </div>
    <% end %>
    <br>
    <%= link_to "back", blogs_path %>

app/views/blogs/edit.html.erb
<%= render 'form', blog: @blog %>

<%= nav_bar fixed: :top, brand: "ROR ASSIGNMENT" do %>
    <%= menu_group do %>
        <%= menu_item "PROJECTS", projects_path %>
        <%= menu_item "BLOGS", blogs_path %>
        <%= menu_item "EMPLOYEE RATINGS", employee_ratings_path %>
        <%= menu_item "EMPLOYEE ROLES", employee_roles_path %>
    <% end %>
    <% end %>

app/views/blogs/index.html.erb
<br>
<br>
<br>
<h1>BLOGS</h1>
 <table border="5" bordercolor=black; background:grey ; color:black >
<thead>


<th>POSTS</th>
<th>Comments</th>
<th>Username</th>
</thead>
<% @blogs.each do |blog| %>
<tr>
<td><%= blog.posts %> </td>



<td><%= blog.comments %></td>
<td><%= blog.username %></td>
<td>

<td><%= link_to "show", blog_path(blog) %></td>
<td><%= link_to "Edit", edit_blog_path(blog) %></td>
<td><%= link_to "delete", blog_path(blog), method: :delete, data: { confirm: "are u sure"} %></td>

</td>
</tr>
<% end %>
</table>
<%= link_to "New Blog",new_blog_path %>

<%= nav_bar fixed: :top, brand: "ROR ASSIGNMENT" do %>
    <%= menu_group do %>
        <%= menu_item "PROJECTS", projects_path %>
        <%= menu_item "BLOGS", blogs_path %>
        <%= menu_item "EMPLOYEE RATINGS", employee_ratings_path %>
        <%= menu_item "EMPLOYEE ROLES", employee_roles_path %>
    <% end %>
    <% end %>

app/views/blogs/new.html.erb
<%= render 'form', blog: @blog %>
<%= nav_bar fixed: :top, brand: "ROR ASSIGNMENT" do %>
    <%= menu_group do %>
        <%= menu_item "PROJECTS", projects_path %>
        <%= menu_item "BLOGS", blogs_path %>
        <%= menu_item "EMPLOYEE RATINGS", employee_ratings_path %>
        <%= menu_item "EMPLOYEE ROLES", employee_roles_path %>
    <% end %>
    <% end %>

app/views/blogs/show.html.erb
<table>
<strong>Posts:</strong>

<%= @blog.posts %>
</p>
<p>

<strong>Comments:</strong>

<%= @blog.comments %>

</p>
<strong>Username:</strong>

<%= @blog.username %>

</p>

<br>
<%= link_to 'Back', :back %>
</table>


<%= nav_bar fixed: :top, brand: "ROR ASSIGNMENT" do %>
    <%= menu_group do %>
        <%= menu_item "PROJECTS", projects_path %>
        <%= menu_item "BLOGS", blogs_path %>
        <%= menu_item "EMPLOYEE RATINGS", employee_ratings_path %>
        <%= menu_item "EMPLOYEE ROLES", employee_roles_path %>
    <% end %>
    <% end %>

app/views/employee_ratings/_form.html.erb
<%= form_for @employee_rating do |f| %>
    <div>
    <%= f.label :userename %>
    <%= f.text_field :username %>
    </div>
    <br>
    <div>
    <%= f.label :rating %>
    <%= f.number_field :rating, {min: 0, max: 5} %>
    </div>
    <br>
    <div>
    <%= f.label :reporting_manager %>
    <%= f.text_field :reporting_manager %>
    </div>
    <br>
    <div>
    <%= f.submit %>
    </div>
    <br>
    <% end %>
    <%= link_to "back", employee_ratings_path %>

app/views/employee_ratings/edit.html.erb
<%= render 'form', employee_rating: @employee_rating %>

<%= nav_bar fixed: :top, brand: "ROR ASSIGNMENT" do %>
    <%= menu_group do %>
        <%= menu_item "PROJECTS", projects_path %>
        <%= menu_item "BLOGS", blogs_path %>
        <%= menu_item "EMPLOYEE RATINGS", employee_ratings_path %>
        <%= menu_item "EMPLOYEE ROLES", employee_roles_path %>
    <% end %>
    <% end %>

app/views/employee_ratings/index.html.erb
<br>
<br>
<br>
<h1>Employee_ratings list</h1>
<table border="5" bordercolor=black; background:grey ; color:black >
<thead>


<th>username</th>
<th>rating</th>
<th>reporting manager</th>
</thead>
<% @employee_ratings.each do |employee_rating| %>
<tr>
<td><%= employee_rating.username %> </td>


<td><%= employee_rating.rating %></td>
<td><%= employee_rating.reporting_manager %></td>
<td>

<%= link_to "show", employee_rating_path(employee_rating) %>
<%= link_to "Edit", edit_employee_rating_path(employee_rating) %>
<%= link_to "delete", employee_rating_path(employee_rating), method: :delete, data: { confirm: "are u sure"} %>

</td>
</tr>
<% end %>
</table>
<%= link_to "New employee_rating",new_employee_rating_path %>


<%= nav_bar fixed: :top, brand: "ROR ASSIGNMENT" do %>
    <%= menu_group do %>
        <%= menu_item "PROJECTS", projects_path %>
        <%= menu_item "BLOGS", blogs_path %>
        <%= menu_item "EMPLOYEE RATINGS", employee_ratings_path %>
        <%= menu_item "EMPLOYEE ROLES", employee_roles_path %>
    <% end %>
    <% end %>

app/views/employee_ratings/new.html.erb
<br>
<br>


<%= render 'form', employee_rating: @employee_rating %>

<%= nav_bar fixed: :top, brand: "ROR ASSIGNMENT" do %>
    <%= menu_group do %>
        <%= menu_item "PROJECTS", projects_path %>
        <%= menu_item "BLOGS", blogs_path %>
        <%= menu_item "EMPLOYEE RATINGS", employee_ratings_path %>
        <%= menu_item "EMPLOYEE ROLES", employee_roles_path %>
    <% end %>
    <% end %>

app/views/employee_ratings/show .html.erb
<table>
<strong>username:</strong>
<%= @employee_rating.name %>
</p>
<p>
<strong>rating:</strong>
<%= @employee_rating.rating %>
</p>
<strong>reporting_manager:</strong>
<%= @employee_rating.reporting_manager %>
</p>
<%= link_to 'Back', :back %>
</table>

<%= nav_bar fixed: :top, brand: "ROR ASSIGNMENT" do %>
    <%= menu_group do %>
        <%= menu_item "PROJECTS", projects_path %>
        <%= menu_item "BLOGS", blogs_path %>
        <%= menu_item "EMPLOYEE RATINGS", employee_ratings_path %>
        <%= menu_item "EMPLOYEE ROLES", employee_roles_path %>
    <% end %>
    <% end %>

app/views/employee_roles/_form.html.erb
<%= form_with(model: employee_role) do |form| %>
  <% if employee_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee_role.errors.count, "error") %> prohibited this employee_role from being saved:</h2>

      <ul>
        <% employee_role.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
  <%= form.label :role %>
  <%= form.select :role, [["Manager", "manager"], ["Tester", "tester"], ["Devloper", "devloper"], ["Lead", "lead"]] %>
</div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to "Back", employee_roles_path %>

app/views/employee_roles/edit.html.erb
<div style="width:400px;margin:0px auto;padding: 20px;text-align:left;background: #FFE5B4; color: black;">


<h2>Editing Employee Role</h2>

<%= render 'form', employee_role: @employee_role %>
<%= nav_bar fixed: :top, brand: "ROR ASSIGNMENT" do %>
    <%= menu_group do %>
        <%= menu_item "PROJECTS", projects_path %>
        <%= menu_item "BLOGS", blogs_path %>
        <%= menu_item "EMPLOYEE RATINGS", employee_ratings_path %>
        <%= menu_item "EMPLOYEE ROLES", employee_roles_path %>
    <% end %>
    <% end %>

app/views/employee_roles/index.html.erb
<br>
<br>
<br>

<h1>Employee Roles</h1>

<table border="5" bordercolor=black; background:grey ; color:black >
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @employee_roles.each do |employee_role| %>
      <tr>
        <td><%= employee_role.name %></td>
        <td><%= employee_role.role%></td>
        <td><%= link_to 'Show', employee_role %></td>
        <td><%= link_to 'Edit', edit_employee_role_path(employee_role) %></td>
        <td><%= link_to 'Destroy', employee_role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee Role', new_employee_role_path %>


<%= nav_bar fixed: :top, brand: "ROR ASSIGNMENT" do %>
  <%= menu_group do %>
      <%= menu_item "PROJECTS", projects_path %>
      <%= menu_item "BLOGS", blogs_path %>
      <%= menu_item "EMPLOYEE RATINGS", employee_ratings_path %>
      <%= menu_item "EMPLOYEE ROLES", employee_roles_path %>
      
  <% end %>
  <% end %>

app/views/employee_roles/new.html.erb
<div style="width:400px;margin:0px auto;padding: 20px;text-align:left;background: #FFE5B4; color: black;">


<h1>New Employee Role</h1>

<%= render 'form', employee_role: @employee_role %>

<%= nav_bar fixed: :top, brand: "ROR ASSIGNMENT" do %>
    <%= menu_group do %>
        <%= menu_item "PROJECTS", projects_path %>
        <%= menu_item "BLOGS", blogs_path %>
        <%= menu_item "EMPLOYEE RATINGS", employee_ratings_path %>
        <%= menu_item "EMPLOYEE ROLES", employee_roles_path %>
    <% end %>
    <% end %>
</div>

app/views/employee_roles/show.html.erb
<table border="5" bordercolor=black; background:grey ; color:black>
        <tr>
            <th align="center">  Employee Name</th>
            <th align="center">  Role</th>
            
            
        </tr>
        <tr>
            <td><%= @employee_role.name %></td>
            <td><%= @employee_role.role%></td>
          
            
        </tr>
</table>

<%= link_to 'Back', employee_roles_path %>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
<br>
    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>
    <br>
    <div>
    <%= f.label :duration %>
    <%= f.text_field :duration %>
    </div>
    <br>
    <div>
    <%= f.label :total_team %>
    <%= f.number_field :total_team %>
    </div>
    <br>
    <div>
    <%= f.submit %>
    </div>
    <% end %>
    <br>
    <%= link_to "back", projects_path %>

app/views/projects/edit.html.erb
<%= render 'form', project: @project %>

<%= nav_bar fixed: :top, brand: "ROR ASSIGNMENT" do %>
    <%= menu_group do %>
        <%= menu_item "PROJECTS", projects_path %>
        <%= menu_item "BLOGS", blogs_path %>
        <%= menu_item "EMPLOYEE RATINGS", employee_ratings_path %>
        <%= menu_item "EMPLOYEE ROLES", employee_roles_path %>
    <% end %>
    <% end %>

app/views/projects/index.html.erb
<br>
<br>
<br>
<h1>Projects list</h1>
<table border="5" bordercolor=black; background:green ; color:black >
<thead>


<th>Name</th>
<th>Duration</th>
<th>Total Team</th>
</thead>
<% @projects.each do |project| %>
<tr>
<td><%= project.name %> </td>


<td><%= project.duration %></td>
<td><%= project.total_team %></td>
<td>

<%= link_to "show", project_path(project) %>
<%= link_to "Edit", edit_project_path(project) %>
<%= link_to "delete", project_path(project), method: :delete, data: { confirm: "are u sure"} %>

</td>
</tr>
<% end %>
</table>
<%= link_to "New Project",new_project_path %>

<%= nav_bar fixed: :top, brand: "ROR ASSIGNMENT" do %>
    <%= menu_group do %>
        <%= menu_item "PROJECTS", projects_path %>
        <%= menu_item "BLOGS", blogs_path %>
        <%= menu_item "EMPLOYEE RATINGS", employee_ratings_path %>
        <%= menu_item "EMPLOYEE ROLES", employee_roles_path %>
        
        
    <% end %>
    <% end %>

app/views/projects/new.html.erb
<%= render 'form', project: @project %>

<%= nav_bar fixed: :top, brand: "ROR ASSIGNMENT" do %>
    <%= menu_group do %>
        <%= menu_item "PROJECTS", projects_path %>
        <%= menu_item "BLOGS", blogs_path %>
        <%= menu_item "EMPLOYEE RATINGS", employee_ratings_path %>
        <%= menu_item "EMPLOYEE ROLES", employee_roles_path %>
    <% end %>
    <% end %>

app/views/projects/show.html.erb
<table>
<strong>Name:</strong>

<%= @project.name %>
</p>
<p>

<strong>Duration:</strong>

<%= @project.duration %>

</p>
<strong>Total Team:</strong>

<%= @project.total_team %>

</p>

<br>
<%= link_to 'Back', :back %>
</table>
<%= nav_bar fixed: :top, brand: "ROR ASSIGNMENT" do %>
    <%= menu_group do %>
        <%= menu_item "PROJECTS", projects_path %>
        <%= menu_item "BLOGS", blogs_path %>
        <%= menu_item "EMPLOYEE RATINGS", employee_ratings_path %>
        <%= menu_item "EMPLOYEE ROLES", employee_roles_path %>
    <% end %>
    <% end %>